# Deep Learning in Medicine
### BMSC-GA 4493, BMIN-GA 3007 
### Lab 2: PyTorch Tutorial and Loss Functions


### Goal of this lab: 
    - Understand Pytorch Tensor, and AutoGrad (Variable is deprecated in the new version of pytorch). 
    - Understand Loss Functions

### What is PyTorch?
It's a Python based scientific computing package targeted as:
* A replacement for numpy to use the power of GPUs
* A deep learning research platform that provides maximum flexibility and speed

### Tensor
It is similar to Numpy Ndarray
<a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html">https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html 


In [1]:
from __future__ import print_function
import torch

#### Check Version of the Pytorch

In [2]:
print(torch.__version__)

1.0.1


#### Tensor Initialization

In [3]:
x = torch.Tensor(6, 2)  # construct a 6x2 matrix, uninitialized

In [4]:
x, x.size()

(tensor([[1.3733e-14, 6.4076e+07],
         [2.0706e-19, 7.3909e+22],
         [2.4176e-12, 1.1625e+33],
         [8.9605e-01, 1.1632e+33],
         [5.6003e-02, 7.0374e+22],
         [5.7453e-44, 0.0000e+00]]), torch.Size([6, 2]))

In [5]:
y = torch.rand(6, 2)  # construct a randomly initialized matrix


In [6]:
y, y.size()

(tensor([[0.1477, 0.9546],
         [0.3455, 0.0534],
         [0.5053, 0.4830],
         [0.4804, 0.5608],
         [0.0185, 0.1296],
         [0.7158, 0.8613]]), torch.Size([6, 2]))

In [7]:
z = torch.ones(7) # construct a matrix of ones

In [8]:
z, z.size()

(tensor([1., 1., 1., 1., 1., 1., 1.]), torch.Size([7]))

#### Operation Example: Addtion
Related reading and reference:
    
* PyTorch documentation:
<a href="http://pytorch.org/docs/0.3.0/"> http://pytorch.org/docs/0.3.0/ </a>


In [9]:
# addition: syntax 1
x + y

tensor([[1.4771e-01, 6.4076e+07],
        [3.4548e-01, 7.3909e+22],
        [5.0533e-01, 1.1625e+33],
        [1.3765e+00, 1.1632e+33],
        [7.4470e-02, 7.0374e+22],
        [7.1580e-01, 8.6125e-01]])

In [10]:
# addition: syntax 2
torch.add(x, y)

tensor([[1.4771e-01, 6.4076e+07],
        [3.4548e-01, 7.3909e+22],
        [5.0533e-01, 1.1625e+33],
        [1.3765e+00, 1.1632e+33],
        [7.4470e-02, 7.0374e+22],
        [7.1580e-01, 8.6125e-01]])

In [11]:
# addition: giving an output tensor
result = torch.Tensor(6, 2)
torch.add(x, y, out=result)

tensor([[1.4771e-01, 6.4076e+07],
        [3.4548e-01, 7.3909e+22],
        [5.0533e-01, 1.1625e+33],
        [1.3765e+00, 1.1632e+33],
        [7.4470e-02, 7.0374e+22],
        [7.1580e-01, 8.6125e-01]])

In [12]:
# addition: in-place
y.add_(x) # adds x to y

tensor([[1.4771e-01, 6.4076e+07],
        [3.4548e-01, 7.3909e+22],
        [5.0533e-01, 1.1625e+33],
        [1.3765e+00, 1.1632e+33],
        [7.4470e-02, 7.0374e+22],
        [7.1580e-01, 8.6125e-01]])

#### Numpy Bridge:
The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

##### Convert Torch Tensor to Numpy

In [13]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [14]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [15]:
a.add_(1) # Remember this is an inplace addition
print(a)
print(b) # see how the numpy array changed in value

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


##### Converting Numpy Array to Torch Tensor

In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


####  Used of CUDA

In [17]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

### Autograd: automatic differentiation
* The autograd package provides automatic differentiation for all operations on Tensors.It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

### Tensor
* torch.Tensor is the central class of the package. If you set its attribute .requires_grad as True, it starts to track all operations on it.
* When you finish your computation you can call .backward() and have all the gradients computed automatically.
* The gradient for this tensor will be accumulated into .grad attribute.
* To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, and to prevent future computation from being tracked.

### Function
* Tensor and Function are interconnected and build up an acyclic graph, that encodes a complete history of computation.
* Each tensor has a .grad_fn attribute that references a Function that has created the Tensor (except for Tensors created by the user - their grad_fn is None).

Related Reading and Reference:
<a href="http://pytorch.org/docs/autograd"> http://pytorch.org/docs/autograd </a>

In [18]:
import torch

In [19]:
x = torch.ones((2, 2), requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [20]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [21]:
print(y.grad_fn)

In [22]:
z = y * y * 2
out = z.mean()
print(z, out)

tensor([[18., 18.],
        [18., 18.]], grad_fn=<MulBackward0>) tensor(18., grad_fn=<MeanBackward1>)


In [23]:
# What's the gradient of X before backward() is performed?
print(x.grad)

None


In [24]:
# What's the correct gradient of X?
out.backward()
print(x.grad)
# Question: How do we get these values?

tensor([[3., 3.],
        [3., 3.]])


In [25]:
print(y.grad)

None


### Loss Functions

 Related Reference: 
<a href="http://pytorch.org/docs/master/nn.html#loss-functions">http://pytorch.org/docs/master/nn.html#loss-functions </a>

#### Mean Squared Error
Question: What is mean square error? What are the inputs? What's the output?

In [26]:
import torch.nn as nn
input = torch.randn((4, 5), requires_grad=True)
target = torch.randn(4, 5)

In [27]:
print(input)
print(target)

tensor([[ 0.1854,  1.0707, -0.9566, -0.4854,  1.9234],
        [ 0.9923,  1.2198, -1.2548,  0.1432, -0.3485],
        [-0.5123,  1.2514,  1.9713,  0.6404, -1.1328],
        [-0.3718, -1.5118, -0.3780,  1.2372, -0.4016]], requires_grad=True)
tensor([[-0.0778,  0.9957, -1.1715,  0.2000,  0.7641],
        [-0.3829,  1.1502, -0.4105, -1.8246, -0.4030],
        [ 1.3442,  0.0252,  0.5594, -0.1343,  1.7321],
        [ 1.6040, -1.9087,  0.3867,  1.0148, -0.2789]])


In [28]:
loss = nn.MSELoss()
output = loss(input, target)
output.backward()

In [29]:
output, input

(tensor(1.4440, grad_fn=<MseLossBackward>),
 tensor([[ 0.1854,  1.0707, -0.9566, -0.4854,  1.9234],
         [ 0.9923,  1.2198, -1.2548,  0.1432, -0.3485],
         [-0.5123,  1.2514,  1.9713,  0.6404, -1.1328],
         [-0.3718, -1.5118, -0.3780,  1.2372, -0.4016]], requires_grad=True))

#### Cross Entropy Loss
Question: What is cross entropy loss? What are the inputs? What's the output?

In [30]:
input = torch.randn((4, 5), requires_grad=True)
target = torch.LongTensor(4).random_(5)
print(input)
print(target)

tensor([[-0.5107,  1.0755, -1.4042,  1.2922,  0.5915],
        [ 0.0748, -0.1743,  0.8988, -0.0042, -1.2319],
        [ 0.6464,  0.4774,  0.2867,  0.6537,  0.6985],
        [-0.5710,  0.2478, -0.8205,  0.3325, -1.4923]], requires_grad=True)
tensor([4, 1, 3, 2])


In [31]:
# Fill in the code to calculate the cross-entropy loss

### Reference:
* Deep Learning with PyTorch: A 60 Minute Blitz:
    <a href="http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html">http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html
    
    
* PyTorch documentation:
<a href="http://pytorch.org/docs/0.3.0/"> http://pytorch.org/docs/0.3.0/ </a>